# version: '3.8'

services:
  backend:
    build: .
    container_name: music_app_backend
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/musicapp
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: music_app_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
